### ISSUE TITLE
Windows 7 32-bit

### ISSUE THREAD

**Issue by sbalhoff** [giMini/PowerMemory#2]
Windows 7 32 bit does not seem to be supported. It maps to mode 132, which is considered a "supported OS" by the script. Then it calls Get-SupportedSystemsInformations, which only initially sets the $start variable for modes 1, 2, 8.1, "2r2", "2016", and "232". This leads to a bunch of errors related to the variables not being set, and the passwords are not retrieved (the usernames are, though). 

The variable '$start' cannot be retrieved because it has not been set.
At C:\users\myuser\Desktop\PowerMemory-master\RWMC\supportedOS\Get-InformationsFromSupportedOS.ps1:29 char:22
+             $value = $start
+                      ~~~~~~
    + CategoryInfo          : InvalidOperation: (start:String) [], RuntimeException
    + FullyQualifiedErrorId : VariableIsUndefined

**Comment by sbalhoff** [comment]
Setting $start to 20 at least works for my local account.

**Comment by giMini** [comment]
Thanks, that was a glitch between version updates and I didn't have a
windows 7 32 bits to retest it.

**Comment by sbalhoff** [comment]
No problem. Thanks. I can test operating systems you don't have in the future if you need me to.
